tellraw @a[score_activate_min=1,score_activate=1,score_admin_min=2,score_admin=2] {"text":""}
tellraw @a[score_admin_min=2,score_admin=2,score_activate_min=1,score_activate=1] {"text":"[Admin Options] ","extra":[{"text":"Random Teams","color":"gold","underlined":"true","clickEvent":{"action":"run_command","value":"/scoreboard players set @p admin 3"},"hoverEvent":{"action":"show_text","value":"Create random teams."}},{"text":" | "},{"text":"Reset Teams","color":"gray","underlined":"true","clickEvent":{"action":"run_command","value":"/scoreboard players set @p admin 5"},"hoverEvent":{"action":"show_text","value":"Reset teams and captains."}},{"text":" | "},{"text":"Start Game","color":"green","underlined":"true","clickEvent":{"action":"run_command","value":"/scoreboard players set @p admin 4"},"hoverEvent":{"action":"show_text","value":"Set all teams to ready."}},{"text":" | "},{"text":"Toggle Menu","color":"yellow","underlined":"true","clickEvent":{"action":"run_command","value":"/scoreboard players set @p admin 6"},"hoverEvent":{"action":"show_text","value":"Toggle the menu visibility (does not affect admin menu)."}},{"text":" | "},{"text":"Remove Admin","color":"blue","underlined":"true","clickEvent":{"action":"run_command","value":"/scoreboard players set @p admin 8"},"hoverEvent":{"action":"show_text","value":"Remove your admin status."}},{"text":" | "},{"text":"Toggle Reset","color":"dark_green","underlined":"true","clickEvent":{"action":"run_command","value":"/scoreboard players set @p admin 10"},"hoverEvent":{"action":"show_text","value":"Toggle auto resting the map."}},{"text":" | "},{"text":"Swap Teams","color":"dark_aqua","underlined":"true","clickEvent":{"action":"run_command","value":"/scoreboard players set @p admin 9"},"hoverEvent":{"action":"show_text","value":"Swap teams and reset the map!"}},{"text":" | "},{"text":"Reset Map","color":"light_purple","underlined":"true","clickEvent":{"action":"run_command","value":"/scoreboard players set @p admin 7"},"hoverEvent":{"action":"show_text","value":"Reset the map to play again!"}}]}
tellraw @a[score_activate_min=1,score_activate=1,score_admin_min=2,score_admin=2] {"text":""}
tellraw @a[team=,score_activate_min=1,score_activate=1,score_menuVis=0,score_admin_min=2,score_admin=2] {"text":"[Team Selection] ","extra":[{"text":"Defender","color":"aqua","underlined":"true","clickEvent":{"action":"run_command","value":"/trigger triggerTeam set 1"},"hoverEvent":{"action":"show_text","value":"Join the Defenders!"}},{"text":" | "},{"text":"Invader","color":"dark_purple","underlined":"true","clickEvent":{"action":"run_command","value":"/trigger triggerTeam set 2"},"hoverEvent":{"action":"show_text","value":"Join the Invaders!"}},{"text":" | "},{"text":"Spectate","color":"gray","underlined":"true","clickEvent":{"action":"run_command","value":"/trigger triggerTeam set 3"},"hoverEvent":{"action":"show_text","value":"Hide from the game."}}]}
tellraw @a[team=!,score_activate_min=1,score_activate=1,score_menuVis=0,score_admin_min=2,score_admin=2] {"text":"[Team Options] ","extra":[{"text":"Toggle Ready","color":"green","underlined":"true","clickEvent":{"action":"run_command","value":"/trigger triggerOption set 1"},"hoverEvent":{"action":"show_text","value":"Set your team as ready (or not)!"}},{"text":" | "},{"text":"Leave Team","color":"gray","underlined":"true","clickEvent":{"action":"run_command","value":"/trigger triggerTeam set -1"},"hoverEvent":{"action":"show_text","value":"Leave your team."}}]}
scoreboard players enable @a[score_activate_min=1,score_activate=1,score_menuVis=0,score_admin_min=2,score_admin=2] triggerTeam
scoreboard players enable @a[score_activate_min=1,score_activate=1,score_menuVis=0,score_admin_min=2,score_admin=2] triggerOption
tellraw @a[score_activate_min=1,score_activate=1,score_admin_min=2,score_admin=2,score_menuVis_min=0,score_menuVis=0] {"text":""}
playsound entity.item.pickup master @a[score_activate_min=1,score_activate=1,score_menuVis_min=0,score_menuVis=1] ~ ~ ~ .2 1.3 .2
scoreboard players set @a[score_activate_min=1,score_activate=1] activate 0
