scoreboard players set @e[type=armor_stand,name=vSpawnerActive1] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive2] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive3] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive4] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive5] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive6] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive7] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive8] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive9] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive10] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive11] var -1 
scoreboard players set @e[type=armor_stand,name=vSpawnerActive12] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive13] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive14] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive15] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive16] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive17] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive18] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive19] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActive20] var -1
scoreboard players set @e[type=armor_stand,name=vSpawnerActiveBlock] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount1] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount2] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount3] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount4] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount5] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount6] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount7] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount8] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount9] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount10] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount11] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount12] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount13] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount14] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount15] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount16] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount17] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount18] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount19] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCount20] var 0
scoreboard players set @e[type=armor_stand,name=vSpawnerCountBlock] var 0
