scoreboard objectives add playerRespawn dummy
scoreboard objectives add playerInGame dummy
scoreboard objectives add playerSinceDeath stat.timeSinceDeath
scoreboard objectives add playerLeave stat.leaveGame
scoreboard objectives add playerSinceLeave